// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Squawk_SecurityML.Model
{
    public class ModelInput
    {
        [ColumnName("Flow ID"), LoadColumn(0)]
        public string Flow_ID { get; set; }


        [ColumnName("Src IP"), LoadColumn(1)]
        public string Src_IP { get; set; }


        [ColumnName("Src Port"), LoadColumn(2)]
        public float Src_Port { get; set; }


        [ColumnName("Dst IP"), LoadColumn(3)]
        public string Dst_IP { get; set; }


        [ColumnName("Dst Port"), LoadColumn(4)]
        public float Dst_Port { get; set; }


        [ColumnName("Protocol"), LoadColumn(5)]
        public float Protocol { get; set; }


        [ColumnName("Timestamp"), LoadColumn(6)]
        public string Timestamp { get; set; }


        [ColumnName("Flow Duration"), LoadColumn(7)]
        public float Flow_Duration { get; set; }


        [ColumnName("Tot Fwd Pkts"), LoadColumn(8)]
        public float Tot_Fwd_Pkts { get; set; }


        [ColumnName("Tot Bwd Pkts"), LoadColumn(9)]
        public float Tot_Bwd_Pkts { get; set; }


        [ColumnName("TotLen Fwd Pkts"), LoadColumn(10)]
        public float TotLen_Fwd_Pkts { get; set; }


        [ColumnName("TotLen Bwd Pkts"), LoadColumn(11)]
        public float TotLen_Bwd_Pkts { get; set; }


        [ColumnName("Fwd Pkt Len Max"), LoadColumn(12)]
        public float Fwd_Pkt_Len_Max { get; set; }


        [ColumnName("Fwd Pkt Len Min"), LoadColumn(13)]
        public float Fwd_Pkt_Len_Min { get; set; }


        [ColumnName("Fwd Pkt Len Mean"), LoadColumn(14)]
        public float Fwd_Pkt_Len_Mean { get; set; }


        [ColumnName("Fwd Pkt Len Std"), LoadColumn(15)]
        public float Fwd_Pkt_Len_Std { get; set; }


        [ColumnName("Bwd Pkt Len Max"), LoadColumn(16)]
        public float Bwd_Pkt_Len_Max { get; set; }


        [ColumnName("Bwd Pkt Len Min"), LoadColumn(17)]
        public float Bwd_Pkt_Len_Min { get; set; }


        [ColumnName("Bwd Pkt Len Mean"), LoadColumn(18)]
        public float Bwd_Pkt_Len_Mean { get; set; }


        [ColumnName("Bwd Pkt Len Std"), LoadColumn(19)]
        public float Bwd_Pkt_Len_Std { get; set; }


        [ColumnName("Flow Byts/s"), LoadColumn(20)]
        public float Flow_Byts_s { get; set; }


        [ColumnName("Flow Pkts/s"), LoadColumn(21)]
        public float Flow_Pkts_s { get; set; }


        [ColumnName("Flow IAT Mean"), LoadColumn(22)]
        public float Flow_IAT_Mean { get; set; }


        [ColumnName("Flow IAT Std"), LoadColumn(23)]
        public float Flow_IAT_Std { get; set; }


        [ColumnName("Flow IAT Max"), LoadColumn(24)]
        public float Flow_IAT_Max { get; set; }


        [ColumnName("Flow IAT Min"), LoadColumn(25)]
        public float Flow_IAT_Min { get; set; }


        [ColumnName("Fwd IAT Tot"), LoadColumn(26)]
        public float Fwd_IAT_Tot { get; set; }


        [ColumnName("Fwd IAT Mean"), LoadColumn(27)]
        public float Fwd_IAT_Mean { get; set; }


        [ColumnName("Fwd IAT Std"), LoadColumn(28)]
        public float Fwd_IAT_Std { get; set; }


        [ColumnName("Fwd IAT Max"), LoadColumn(29)]
        public float Fwd_IAT_Max { get; set; }


        [ColumnName("Fwd IAT Min"), LoadColumn(30)]
        public float Fwd_IAT_Min { get; set; }


        [ColumnName("Bwd IAT Tot"), LoadColumn(31)]
        public float Bwd_IAT_Tot { get; set; }


        [ColumnName("Bwd IAT Mean"), LoadColumn(32)]
        public float Bwd_IAT_Mean { get; set; }


        [ColumnName("Bwd IAT Std"), LoadColumn(33)]
        public float Bwd_IAT_Std { get; set; }


        [ColumnName("Bwd IAT Max"), LoadColumn(34)]
        public float Bwd_IAT_Max { get; set; }


        [ColumnName("Bwd IAT Min"), LoadColumn(35)]
        public float Bwd_IAT_Min { get; set; }


        [ColumnName("Fwd PSH Flags"), LoadColumn(36)]
        public string Fwd_PSH_Flags { get; set; }


        [ColumnName("Bwd PSH Flags"), LoadColumn(37)]
        public float Bwd_PSH_Flags { get; set; }


        [ColumnName("Fwd URG Flags"), LoadColumn(38)]
        public float Fwd_URG_Flags { get; set; }


        [ColumnName("Bwd URG Flags"), LoadColumn(39)]
        public float Bwd_URG_Flags { get; set; }


        [ColumnName("Fwd Header Len"), LoadColumn(40)]
        public float Fwd_Header_Len { get; set; }


        [ColumnName("Bwd Header Len"), LoadColumn(41)]
        public float Bwd_Header_Len { get; set; }


        [ColumnName("Fwd Pkts/s"), LoadColumn(42)]
        public float Fwd_Pkts_s { get; set; }


        [ColumnName("Bwd Pkts/s"), LoadColumn(43)]
        public float Bwd_Pkts_s { get; set; }


        [ColumnName("Pkt Len Min"), LoadColumn(44)]
        public float Pkt_Len_Min { get; set; }


        [ColumnName("Pkt Len Max"), LoadColumn(45)]
        public float Pkt_Len_Max { get; set; }


        [ColumnName("Pkt Len Mean"), LoadColumn(46)]
        public float Pkt_Len_Mean { get; set; }


        [ColumnName("Pkt Len Std"), LoadColumn(47)]
        public float Pkt_Len_Std { get; set; }


        [ColumnName("Pkt Len Var"), LoadColumn(48)]
        public float Pkt_Len_Var { get; set; }


        [ColumnName("FIN Flag Cnt"), LoadColumn(49)]
        public float FIN_Flag_Cnt { get; set; }


        [ColumnName("SYN Flag Cnt"), LoadColumn(50)]
        public float SYN_Flag_Cnt { get; set; }


        [ColumnName("RST Flag Cnt"), LoadColumn(51)]
        public float RST_Flag_Cnt { get; set; }


        [ColumnName("PSH Flag Cnt"), LoadColumn(52)]
        public float PSH_Flag_Cnt { get; set; }


        [ColumnName("ACK Flag Cnt"), LoadColumn(53)]
        public float ACK_Flag_Cnt { get; set; }


        [ColumnName("URG Flag Cnt"), LoadColumn(54)]
        public float URG_Flag_Cnt { get; set; }


        [ColumnName("CWE Flag Count"), LoadColumn(55)]
        public float CWE_Flag_Count { get; set; }


        [ColumnName("ECE Flag Cnt"), LoadColumn(56)]
        public float ECE_Flag_Cnt { get; set; }


        [ColumnName("Down/Up Ratio"), LoadColumn(57)]
        public float Down_Up_Ratio { get; set; }


        [ColumnName("Pkt Size Avg"), LoadColumn(58)]
        public float Pkt_Size_Avg { get; set; }


        [ColumnName("Fwd Seg Size Avg"), LoadColumn(59)]
        public float Fwd_Seg_Size_Avg { get; set; }


        [ColumnName("Bwd Seg Size Avg"), LoadColumn(60)]
        public float Bwd_Seg_Size_Avg { get; set; }


        [ColumnName("Fwd Byts/b Avg"), LoadColumn(61)]
        public float Fwd_Byts_b_Avg { get; set; }


        [ColumnName("Fwd Pkts/b Avg"), LoadColumn(62)]
        public float Fwd_Pkts_b_Avg { get; set; }


        [ColumnName("Fwd Blk Rate Avg"), LoadColumn(63)]
        public float Fwd_Blk_Rate_Avg { get; set; }


        [ColumnName("Bwd Byts/b Avg"), LoadColumn(64)]
        public float Bwd_Byts_b_Avg { get; set; }


        [ColumnName("Bwd Pkts/b Avg"), LoadColumn(65)]
        public float Bwd_Pkts_b_Avg { get; set; }


        [ColumnName("Bwd Blk Rate Avg"), LoadColumn(66)]
        public float Bwd_Blk_Rate_Avg { get; set; }


        [ColumnName("Subflow Fwd Pkts"), LoadColumn(67)]
        public float Subflow_Fwd_Pkts { get; set; }


        [ColumnName("Subflow Fwd Byts"), LoadColumn(68)]
        public float Subflow_Fwd_Byts { get; set; }


        [ColumnName("Subflow Bwd Pkts"), LoadColumn(69)]
        public float Subflow_Bwd_Pkts { get; set; }


        [ColumnName("Subflow Bwd Byts"), LoadColumn(70)]
        public float Subflow_Bwd_Byts { get; set; }


        [ColumnName("Init Fwd Win Byts"), LoadColumn(71)]
        public float Init_Fwd_Win_Byts { get; set; }


        [ColumnName("Init Bwd Win Byts"), LoadColumn(72)]
        public float Init_Bwd_Win_Byts { get; set; }


        [ColumnName("Fwd Act Data Pkts"), LoadColumn(73)]
        public float Fwd_Act_Data_Pkts { get; set; }


        [ColumnName("Fwd Seg Size Min"), LoadColumn(74)]
        public float Fwd_Seg_Size_Min { get; set; }


        [ColumnName("Active Mean"), LoadColumn(75)]
        public float Active_Mean { get; set; }


        [ColumnName("Active Std"), LoadColumn(76)]
        public float Active_Std { get; set; }


        [ColumnName("Active Max"), LoadColumn(77)]
        public float Active_Max { get; set; }


        [ColumnName("Active Min"), LoadColumn(78)]
        public float Active_Min { get; set; }


        [ColumnName("Idle Mean"), LoadColumn(79)]
        public float Idle_Mean { get; set; }


        [ColumnName("Idle Std"), LoadColumn(80)]
        public float Idle_Std { get; set; }


        [ColumnName("Idle Max"), LoadColumn(81)]
        public float Idle_Max { get; set; }


        [ColumnName("Idle Min"), LoadColumn(82)]
        public float Idle_Min { get; set; }


        [ColumnName("Label"), LoadColumn(83)]
        public string Label { get; set; }


    }
}
