name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install APT Dependencies
      run: sudo apt-get update && apt install -y --allow-unauthenticated libpcap0.8
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/Squawk-Security.sln
    - name: Build
      run: dotnet build src/Squawk-Security.sln --no-restore
    - name: Test
      run: dotnet test src/Squawk-Security.sln --no-build --verbosity normal
